server:
  port: 8090
  servlet:
    context-path: /spring-api
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

#logging:
#  level:
#    web: DEBUG
#    fr: DEBUG

spring:
  config:
    import: classpath:private.yml # Variables privées à ne pas diffuser.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

security-configuration:
  soffit:
    jwt.signatureKey: "=== Signature Key ===" # Variable privée surchargée dans private.yml.
  cors:
    enable: true
    allow-credentials: true
    allowed-origins: >
      http://localhost:5173,
      http://10.209.28.14:5173,
      https://*.giprecia.net
    exposed-headers: >
      x-auth-token,
      x-requested-with,
      x-xsrf-token
    allowed-headers: >
      content-type,
      authorization,
      x-com-persist,
      X-Auth-Token,
      x-auth-token,
      x-requested-with,
      x-xsrf-token
    allowed-methods: >
      GET
