#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ./mvnw notice:check; then
  echo "Notice OK"
else
  echo "Fix notice"
  ./mvnw notice:generate
fi
if ./mvnw license:check; then
  echo "License OK"
else
  echo "Fix license"
  ./mvnw license:format
fi
yarn lint-staged
